MySQL:
  database: 'pluginData'
  host: 'localhost'
  user: 'BauPlugin'
  password: 'r0gltuXNFEqKDCy3'

worldEdit:
  maxBlockPerSecond: 5000
coordinates:
  tbs:
    paste: 
    # remember that the North-Position may have the same distance to the TestBlock faing to North 
    # like the South_Position to the TB facing to South! (else you will get some messy stuff)
      N: #standard for other paste-actions(e.g. pasting the floor)
        plot1: -101 8 17   #plotID = name of the region -> First make region over the single plots, then over all plots
        plot2: -209 8 17
        plot3: -317 8 17
      S:
        plot1: -101 8 16   #plotID = name of the region -> First make region over the single plots, then over all plots
        plot2: -209 8 16
        plot3: -317 8 16
    front:
      N:
        plot1: -101 8 41   #plotID = name of the region -> First make region over the single plots, then over all plots
        plot2: -209 8 41
        plot3: -317 8 41
      S:
        plot1: -101 8 -8   #plotID = name of the region -> First make region over the single plots, then over all plots
        plot2: -209 8 -8
        plot3: -317 8 -8
    sizes:
      1:
        x: 23
        y: 23
        z: 23
        shields: 8
      2:
        x: 45
        y: 32
        z: 33
        shields: 12
      3:
        x: 67
        y: 41
        z: 37
        shields: 16
  spawn: plot2
  teleport:
    plot1: -100.5 8 17.0   #plotID = name of the region -> First make region over the single plots, then over all plots
    plot2: -208.5 8 17.0
    plot3: -316.5 8 17.0
    testplot1: -100.5 8 17.0   #plotID = name of the region -> First make region over the single plots, then over all plots
    testplot2: -208.5 8 17.0
    testplot3: -316.5 8 17.0
  worldBorder:
    min: -370 8 -65
    max: -48 68 98
plottemplate: BauGsVorlage #If you want to update this, change the worldname! Else User cannot get a new plot
plotreset:
  pasteGround: true
  schemfiles:
    plot1: ground
    plot2: ground
    plot3: ground
schempath: /root/test/schematics
tntReload:
  maxTnt: 1000
  materialType: TNT_MINECART
  timeout: 5                 #antispam
fernzuender: WOODEN_HOE
testworlds:
  template: BauGsVorlage