MySQL:
  database: 'pluginData'
  host: 'localhost'
  user: 'BauPlugin'
  password: 'r0gltuXNFEqKDCy3'

worldEdit:
  maxBlockPerSecond: 5000
plottemplate: BauGsVorlage #If you want to update this, change the worldname! Else User cannot get a new plot
schempath: /root/test/schematics
tntReload:
  maxTnt: 1000
  materialType: TNT_MINECART
  timeout: 5                 #antispam
fernzuender: WOODEN_HOE
testworlds:
  template: BauGsVorlage