name: PluginBau
version: 2.0
author: FREE2WIN
main: de.AS.Bau.Main
api-version: 1.15
depend: [WorldEdit,WorldGuard]
description: Bauplugin
commands:
   stats:
      description: aab
   gs:
     usage: /<command> [list, info , tp, add, addtemp, remove] [PlayerName] [TempTime]
   tnt:
     usage: /<command>
     description: Enable/Disable Tnt
   gui:
      usage: /<command>
      description: Open a GUI for your plot.
   tbs:
      usage: /<command> [1,2,3,4] [N,S] [N,S,F,R]
      description: Opens Tnt-Slave
   sl:
      usage: /<command>
      description: turn Stoplag on/off
   dt:
      usage: /<command>
      description: Turns Design-Tool on and off.
   ds:
      usage: /<command>
      description: Gives you an DebugStick
   debugstick:
      usage: /<command>
      description: Gives you an DebugStick
   chest:
      usage: /<command>
      description: Gives you an TNT Chest
      aliases: [tntchest]
   delcon:
      description: delete Plot.
   baureload:
      description: handling
   particles:
      description: toggle Particles
      aliases: [partikel,p]
      usage: /<command> [on|off]
   tr:
     description: tntReload command
     aliases: [tntReload,cannonReload,cr]
     usage: /<command>
   clear:
     description: Resets your inventory
     
     
permissions:
  bau.*:
    default: op
    childrens:
      bau.move.bypass: true
      bau.delete.bypass: true
      bau.build.bypass: true
  bau.move.bypass:
    default: false
  bau.delete.bypass:
    default: false
  bau.build.bypass:
    default: false
    
    
    