name: PluginBau
version: 2.0
author: FREE2WIN
main: net.wargearworld.bau.Main
api-version: 1.15
depend: [WorldEdit,WorldGuard, TheDependencyPlugin]
description: Bauplugin
commands:
   stats:
      description: aab
   gs:
     usage: /<command> [list, info , tp, add, addtemp, remove] [PlayerName] [TempTime]
   tnt:
     usage: /<command>
     description: Enable/Disable Tnt
   gui:
      usage: /<command>
      description: Open a GUI for your plot.
   tbs:
      usage: /<command> [undo,last,1,2,3,4] [N,S] [N,S,F,R]
      description: Opens Tnt-Slave
   sl:
      usage: /<command>
      description: turn Stoplag on/off
      aliases: [stoplag]
   dt:
      usage: /<command>
      description: Turns Design-Tool on and off.
   ds:
      usage: /<command>
      description: Gives you an DebugStick
   debugstick:
      usage: /<command>
      description: Gives you an DebugStick
   chest:
      usage: /<command>
      description: Gives you an TNT Chest
      aliases: [tntchest]
   plotreset:
      description: delete Plot.
   baureload:
      description: handling
   particles:
      description: toggle Particles
      aliases: [partikel,p]
      usage: /<command> [on|off]
   tr:
     description: tntReload command
     aliases: [tntreload,cannonreload,cr]
     usage: /<command>
   clear:
     description: Resets your inventory
   worlds:
     description: Resets your worlds
   waterremover:
     description: toggle Waterremover
     aliases: [wr]
   worldfuscator:
     description: toggle WorldFuscator
     aliases: [wf,blockhider,awdl]


permissions:
  bau.*:
    default: op
    childrens:
      bau.move.bypass: true
      bau.delete.bypass: true
      bau.build.bypass: true
  bau.move.bypass:
    default: op
  bau.delete.bypass:
    default: op
  bau.build.bypass:
    default: op
  bau.rights.bypass:
    default: op
    
    
    