name: PluginBau
version: 1.0
author: FREE2WIN
main: de.AS.Bau.Main
api-version: 1.15
depend: [WorldEdit,WorldGuard]
commands:
   stats:
      description:
   gs:
     usage: /<command> [list, info , tp, add, addtemp, remove] [PlayerName] [TempTime]
   tnt:
     usage: /<command>
     description: Enable/Disable Tnt
   gui:
      usage: /<command>
      description: Open a GUI for your plot.
   tbs:
      usage: /<command> [1,2,3,4] [N,S] [N,S,F,R]
      description: Opens Tnt-Slave
   sl:
      usage: /<command>
      description: turn Stoplag on/off
   dt:
      usage: /<command>
      description: Turns Design-Tool on and off.
   ds:
      usage: /<command>
      description: Gives you an DebugStick
   debugstick:
      usage: /<command>
      description: Gives you an DebugStick
   chest:
      usage: /<command>
      description: Gives you an TNT Chest
      aliases: [tntchest]
   delcon:
      description: delete Plot.
   bau:
      description: handling